## TF Syntax and usage

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


### Constant tensor 

In [9]:
h = tf.constant('H ')

In [10]:
w = tf.constant('TF')

In [11]:
type(h)

tensorflow.python.framework.ops.Tensor

In [12]:
print(h)

Tensor("Const_6:0", shape=(), dtype=string)


In [13]:
with tf.Session() as sess:
    r = sess.run(h + w)

In [14]:
print(r)

b'H TF'


### Addition

In [15]:
a = tf.constant(10)
b = tf.constant(20)

In [16]:
type(a)

tensorflow.python.framework.ops.Tensor

In [17]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [18]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [19]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [20]:
result

30

### Generating arrays

In [21]:
const = tf.constant(10)

In [22]:
fill_mat = tf.fill((4,4), 10)

In [24]:
zeros = tf.zeros((4,4))

In [25]:
ones = tf.ones((4,4))

In [28]:
randoms_normal = tf.random_normal((4,4), mean=0, stddev=1.0)

In [29]:
randoms_uniform = tf.random_uniform((4,4), minval=0, maxval=1)

In [30]:
zeros

<tf.Tensor 'zeros_1:0' shape=(4, 4) dtype=float32>

In [31]:
ops = [const, fill_mat, zeros, ones, randoms_normal, randoms_uniform]

### Interactive session

In [32]:
sess = tf.InteractiveSession()

In [35]:
for op in ops:
    print(sess.run(op), end='\n\n')

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

[[ 1.63355243  0.56504178  0.13132364  1.86392605]
 [ 0.43108353  0.95267731 -0.51273245  0.17270051]
 [-0.59199488  1.9148773   0.75107425  0.18348669]
 [ 0.02626057  0.57956123 -0.13421547 -1.53819418]]

[[ 0.58241975  0.71928275  0.55670106  0.07963312]
 [ 0.91462421  0.4189589   0.89775968  0.94909525]
 [ 0.80639231  0.00434482  0.47240829  0.23644304]
 [ 0.58895946  0.16376519  0.90062571  0.23592257]]



### Matrix multiplication

In [36]:
a = tf.constant([ [1,2], [3,4] ])

In [37]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [39]:
b = tf.constant([ [2], [200] ])

In [40]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [41]:
r = tf.matmul(a, b)

In [42]:
sess.run(r)

array([[402],
       [806]])

In [43]:
r.eval()

array([[402],
       [806]])

## Graphs

In [44]:
n1 = tf.constant(1)

In [45]:
n2 = tf.constant(2)

In [46]:
n3 = n1 + n2

In [47]:
sess.run(n3)

3

In [48]:
print(n3)

Tensor("add_4:0", shape=(), dtype=int32)


### Default graph instance

In [49]:
print(tf.get_default_graph())

In [50]:
g = tf.Graph()

In [51]:
print(g)

In [55]:
g1 = tf.get_default_graph()
g2 = tf.Graph()

In [57]:
with g2.as_default():
    print(g2 is tf.get_default_graph())

True


In [58]:
g2 is tf.get_default_graph()

False

## Variables and placeholders

In [59]:
tens = tf.random_uniform((4,4), minval=0, maxval=1)

In [60]:
tens

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [61]:
var = tf.Variable(initial_value=tens)

In [62]:
print(var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [64]:
init = tf.global_variables_initializer()

In [65]:
sess.run(init)

In [66]:
sess.run(var)

array([[ 0.04164684,  0.91593456,  0.87786245,  0.32245255],
       [ 0.40200162,  0.57591379,  0.88480008,  0.60542369],
       [ 0.09817815,  0.27261019,  0.40738976,  0.95338297],
       [ 0.66565692,  0.21332932,  0.17353368,  0.14421809]], dtype=float32)

In [69]:
ph = tf.placeholder(tf.float32, shape=(None, 5))

In [70]:
print(ph)

Tensor("Placeholder_1:0", shape=(?, 5), dtype=float32)
